# Generated by Django 4.0.3 on 2022-04-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parentezco',
        ),
    ]
