# Generated by Django 4.0.3 on 2022-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_familiar_dni_familiar_parentezco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='fechaDeNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
